Repository lob/pharos, pull requests merged in 2019-07, with the labels that each got.

#14 feat(cli): add pharos clusters sync command
  pkg/pharos/cli/cli.go
  pkg/pharos/cli/cli_test.go
  pkg/pharos/cmd/delete.go
  pkg/pharos/cmd/get.go
  pkg/pharos/cmd/list.go
  pkg/pharos/cmd/root.go
  pkg/pharos/cmd/sync.go
  pkg/pharos/cmd/sync_test.go
Labels: Approved

#22 feat(authorization): add authorization to endpoints
  pkg/pharos-api-server/authentication/authentication_test.go
  pkg/pharos-api-server/authorization/authorization.go
  pkg/pharos-api-server/authorization/authorization_test.go
  pkg/pharos-api-server/clusters/routes.go
  pkg/pharos-api-server/clusters/routes_test.go
  pkg/pharos-api-server/config/config.go
  pkg/pharos-api-server/config/config_test.go
  pkg/pharos-api-server/server/server.go
  pkg/pharos-api-server/server/server_test.go
Labels: Approved

#20 feat(cli): add pharos clusters create command
  pkg/pharos/api/pharos.go
  pkg/pharos/api/pharos_test.go
  pkg/pharos/cli/cli.go
  pkg/pharos/cmd/create.go
  pkg/pharos/cmd/create_test.go
  pkg/pharos/cmd/delete.go
  pkg/pharos/cmd/list.go
  pkg/pharos/cmd/root.go
  pkg/pharos/cmd/switch.go
  pkg/pharos/cmd/update.go
Labels: Approved

#21 feat(cli): add authentication to cli to handle running on EC2 instances in our clusters
  pkg/pharos/api/client.go
  pkg/pharos/config/config.go
Labels: Approved

#23 feat(cli): add pharos setup command
  pkg/pharos/cmd/current_test.go
  pkg/pharos/cmd/root.go
  pkg/pharos/cmd/root_test.go
  pkg/pharos/cmd/setup.go
  pkg/pharos/cmd/setup_test.go
  pkg/pharos/cmd/switch_test.go
  pkg/pharos/config/config.go
  pkg/pharos/config/config_test.go
Labels: Approved

#26 feat(Dockerfile): add migration binary to docker image to allow for easy migrations
  Dockerfile
Labels: Approved

#25 fix(kubeconfig): decode cluster-authority-data returned by server
  pkg/pharos/cli/kubeconfig.go
Labels: Approved, Bug

#24 chore(release): add release functionality
  .circleci/config.yml
  .goreleaser.yml
  LICENSE
  Makefile
  README.md
  pkg/pharos/cmd/root.go
Labels: Approved

#27 fix(circleci): fix workflow tag trigger issue
  .circleci/config.yml
Labels: Approved

#28 fix(version): remove default version
  pkg/pharos/cmd/root.go
Labels: LGTM'd Once

#29 feat(completion): add completion command to support shell autocomplete
  pkg/pharos/cmd/completion.go
  pkg/pharos/cmd/root.go
Labels: Approved

#30 chore(clusters): add ability to export clusters cmd
  pkg/pharos/cmd/clusters.go
  pkg/pharos/cmd/root.go
Labels: Approved
